### ISSUE TITLE
export 'getPlatform' was not found in 'quasar'

### ISSUE THREAD

**Issue by yieme** [quasarframework/quasar-template-nuxt#2]
It's awesome that you are looking to support nuxt with quasar. I think this has the potential to be a killer combination :-) 

Hi I'm getting an `export 'getPlatform' was not found in 'quasar'` error.

Running:
- node 9.2.0
- quasar cli v0.6.4
- quasar v0.15.0
- npm 5.5.1
- yarn 1.1.0

Created a project with:

```sh
quasar init @quasarframework/quasar-template-nuxt my-project
cd my-project
npm install
```

Which ended with a warning:
```
npm WARN quasar-framework@0.15.0 requires a peer of vue@^2.5.0 but none is installed. You must install peer dependencies yourself.
```

`quasar dev` produced:
```
Error: Cannot find module '@nuxtjs/youch'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jim/projects/tmp/quasar-nuxt/node_modules/nuxt/dist/nuxt.js:30:29)
```

Tried again this time with yarn. Installed with:

```sh
quasar init @quasarframework/quasar-template-nuxt my-project2
cd my-project2
yarn
```

`quasar dev` compiled with 1 warning. 

```
warning  in ./middleware/userAgent.js
5:16-27 "export 'getPlatform' was not found in 'quasar'
 OPEN  http://localhost:3000
```

Opening `http://localhost:3000` in Chrome the page displays:

```
ReferenceError

navigator is not defined
```

and

```
node_modules/quasar-framework/dist/quasar.mat.esm.js

function getUserAgent () {
  return (navigator.userAgent || navigator.vendor || window.opera).toLowerCase()
}
```

With `return (navigator.userAgent || navigator.vendor || window.opera).toLowerCase()` highlighted.

Any thoughts?

**Comment by rstoenescu** [comment]
Hi,

Please wait until this is ready. At the moment this is just some initial scaffolding, marked as WIP (work in progress).
