### ISSUE TITLE
template work error!

### ISSUE THREAD

**Issue by owey0312** [quasarframework/quasar-template-nuxt#3]
![image 2](https://user-images.githubusercontent.com/32464691/34159777-5b8a443e-e505-11e7-975f-49beab1eac95.png)
![image 1](https://user-images.githubusercontent.com/32464691/34159686-0fd2d114-e505-11e7-900b-3f4ac6934f79.png)

as show above, when i used the template as your steps, it show these errors, i do not know why so.

**Comment by rstoenescu** [comment]
Hi, it is still labelled as "Work in progress". Not ready for the public yet.
